version: "3.9"

services:

  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    restart: always
    networks:
      - inception
    expose:
      - 3306
    volumes:
      - mariadb_data:/var/lib/mysql

  wordpress:
    depends_on:
      - mariadb
    build: requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - inception
    expose:
      - 9000

  nginx:
    depends_on:
      - wordpress
    build: requirements/nginx
    container_name: nginx
    env_file:
      - .env
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - inception

networks:
  inception:
    driver: bridge

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/ctw02485/42/Inception/data/wordpress
      o: bind
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/ctw02485/42/Inception/data/mysql
      o: bind