version: "3.9"

services:

  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    restart: always
    networks:
      - inception
    expose:
      - 3306

  wordpress:
    depends_on:
      - mariadb
    build: requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    restart: always
    networks:
      - inception

  nginx:
    depends_on:
      - wordpress
    build: requirements/nginx
    container_name: nginx
    env_file:
      - .env
    ports:
      - 443:443
    restart: always
    networks:
      - inception

networks:
  inception: