version: "3.9"

services:

  mariadb:
    build: requirements/mariadb
    env_file:
      - .env
    restart: always
    networks:
      - inception
    expose:
      - 3306

  nginx:
    build: requirements/nginx
    env_file:
      - .env
    ports:
      - 443:443
    restart: always
    networks:
      - inception

  wordpress:
    build: requirements/wordpress
    env_file:
      - .env
    restart: always
    networks:
      - inception

networks:
  inception: